<a href="https://colab.research.google.com/github/fahmi54321/deep_learning_ann/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')

# iloc[row,column]
#  : = semua data,
#  :-1 = semua data, kecuali data terakhir,
#  -1 = data terakhir,
# :,3 = semua data kolom index 3

x = dataset.iloc[:,3 :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
# :,2 = semua data kolom index 2
x[:, 2] = le.fit_transform(x[:, 2])

In [7]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# [1] = index kolom ke 1
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [12]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [13]:
# 6 = units = the number of neurons or the number of hidden neurons
# how do we know how many neurons we want ?
# should we just experiment / is is just based on experimentation
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [14]:
# 6 = units = the number of neurons or the number of hidden neurons
# how do we know how many neurons we want ?
# should we just experiment / is is just based on experimentation
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [15]:
# 1 = units = one output neuron encoding the dependent variable
# dikarenakan dependent variable (dataset kolom exited) hanya berisi output 0 atau 1
# sigmoid = activation binary classification
# softmax = activation non binary classification
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [16]:
# binary_crossentropy = predict loss function binary classification
# categorical_crossentropy = predict loss function non binary classification
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [17]:
# batch_size = gives exactly the number of predictions you want to have in the batch to be compared
#              to that same number of real results
# 32 = the classic value of the batch size that is usually chosen

ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 4s 7ms/step - loss: 0.6739 - accuracy: 0.6204
Epoch 2/100
250/250 [==============================] - 2s 9ms/step - loss: 0.4818 - accuracy: 0.8050
Epoch 3/100
250/250 [==============================] - 2s 8ms/step - loss: 0.4538 - accuracy: 0.8077
Epoch 4/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4411 - accuracy: 0.8081
Epoch 5/100
250/250 [==============================] - 2s 9ms/step - loss: 0.4309 - accuracy: 0.8116
Epoch 6/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4218 - accuracy: 0.8165
Epoch 7/100
250/250 [==============================] - 1s 6ms/step - loss: 0.4103 - accuracy: 0.8225
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3988 - accuracy: 0.8311
Epoch 9/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3887 - accuracy: 0.8371
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3806 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [21]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

1/1 [==============================] - 0s 235ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [23]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)

# concatenate => menggabungkan array dalam satu baris
# concatenate ((a1, a2, ..), axis)
# concatenate axis => 0 = wanna do a vertical concatenation
#                     1 = wanna do a horizontal concatenation

y_pred_reshape = y_pred.reshape(len(y_pred),1) # convert dari tampilan horizontal ke vertikal
y_reshape = y_test.reshape(len(y_test),1) # convert dari tampilan horizontal ke vertikal
print(np.concatenate((y_pred_reshape,y_reshape), 1))

# y_pred_reshape = purchased predict
# y_reshape = purchased real

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)

accuracy_score(y_test, y_pred)

# 1518 the number of correct predictions that the purchased is 0.
# 199 the number of correct predictions that the purchased is 1
# 77 (top right) the number of incorrect predictions that the purchased is 1.
# 206 (bottom left) the number of incorrect predictions that the purchased is 0.



[[1518   77]
 [ 206  199]]


0.8585